### ISSUE TITLE
add audio download + volume normalize

### ISSUE THREAD

**Issue by brjppru** [alvicsam/ytap-python#8]
--- a/app/main.py
+++ b/app/main.py
@@ -49,7 +49,7 @@ def download_video(id, url):
     :return: name of the video
     """
     video_filename = f"/tmp/video-{id}.mp4"
-    cmd_download = f"youtube-dl --newline -f worst {url} -o {video_filename}"
+    cmd_download = f"youtube-dl -vv -x --newline -f worst {url} -o {video_filename}"

**add only audio download, not audio + video (trafic burndown)**

     cmd_name = f"youtube-dl --skip-download --get-title --no-warnings {url}"
     try:
         code = subprocess.run(cmd_download.split())
@@ -67,7 +67,7 @@ def get_audio_from_video(id):
     Extract audio with ffmpeg
     """
     audio_filename = f"/tmp/audio-{id}.mp3"
-    cmd = f"ffmpeg -i /tmp/video-{id}.mp4 -q:a 0 -map a {audio_filename}"
+    cmd = f"ffmpeg -i /tmp/video-{id}.mp4 -q:a 0 -ac 1 -filter:a dynaudnorm -map a {audio_filename}"

**normalize audio volume + convert to mono**

**Comment by alvicsam** [comment]
Hey @brjppru , thank you for the issue.

`-x` option for youtube-dl will extract audio from already downloaded video but the idea is nice!  So I applied the fix in https://github.com/alvicsam/ytap-python/pull/9

I tried the second option for `get_audio_from_video(id)` but I didn't like the result. Sometimes I can download music so converting to mono makes sound worse. So it's just a matter of taste :)
